package com.stv.launcher.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCREEN_INFO.
 */
public class ScreenInfo {

    private Integer id;
    private String tag;
    private String name;
    private String fragment_class;

    public ScreenInfo() {
    }

    public ScreenInfo(Integer id, String tag, String name, String fragment_class) {
        this.id = id;
        this.tag = tag;
        this.name = name;
        this.fragment_class = fragment_class;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFragment_class() {
        return fragment_class;
    }

    public void setFragment_class(String fragment_class) {
        this.fragment_class = fragment_class;
    }

}
